### ISSUE TITLE
Java 11 compatibility

### ISSUE THREAD

**Issue by aalmiray** [AdoptOpenJDK/jsplitpkgscan-maven-plugin#14]
The project POM states JDK 12 as source/target compatibility. Are there any hard restrictions that require JDK 12 as a minimum? Is it possible to change this to JDK 11?

**Comment by reinhapa** [comment]
No, I'm ok to change that..

**Comment by aalmiray** [comment]
FWIW the `jsplitpkgscan-1.1.0-SNAPSHOT` dependency (unreleased as it is) also declares JDK 12 compatibility

https://github.com/AdoptOpenJDK/jsplitpkgscan/blob/master/build.gradle#L16
